AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String

  EnvironmentName:
    Type: String

  VisibilityTimeout:
    Type: Number

  MessageRetentionPeriod:
    Type: Number

Resources:
  Queue:
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: { Ref: MessageRetentionPeriod }
      VisibilityTimeout: { Ref: VisibilityTimeout }

Outputs:
  QueueUrl:
    Value: { Ref: Queue }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ProjectName }
            - { Ref: EnvironmentName }
            - queue
            - url
  QueueArn:
    Value:
      "Fn::GetAtt": [Queue, Arn]
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ProjectName }
            - { Ref: EnvironmentName }
            - queue
            - arn
