AWSTemplateFormatVersion: "2010-09-09"

Description: A 4-subnet (2 public, 2 private) standard VPC.

Parameters:
  ProjectName:
    Type: String
    Description: Name for this project; e.g. downtime-notifier, dynamodb-scaler

  EnvironmentName:
    Type: String
    Description: Name for this environment; e.g. development, staging, production

  VpcCidr:
    Type: String
    Description: A network CIDR e.g. "10.0.0.0/16"

  PublicSubnetAZ0Cidr:
    Type: String
    Description: A subnet CIDR e.g. "10.0.0.0/24"

  PrivateSubnetAZ0Cidr:
    Type: String
    Description: A subnet CIDR e.g. "10.0.10.0/24"

  PublicSubnetAZ1Cidr:
    Type: String
    Description: A subnet CIDR e.g. "10.0.1.0/24"

  PrivateSubnetAZ1Cidr:
    Type: String
    Description: A subnet CIDR e.g. "10.0.11.0/24"


Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: True
      EnableDnsHostnames: True
      InstanceTenancy: default
      CidrBlock: { Ref: VpcCidr }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ProjectName }
                - { Ref: EnvironmentName }
                - "vpc"

  DHCPSettings:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainNameServers:  [ "AmazonProvidedDNS" ]
      DomainName:  ec2-internal

  DHCPSettingsAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      VpcId: { "Ref" : "Vpc" }
      DhcpOptionsId: { "Ref" : "DHCPSettings" }

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ProjectName }
                - { Ref: EnvironmentName }
                - "internetgw"

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: { "Ref": "Vpc" }
      InternetGatewayId : { "Ref" : "InternetGateway" }

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: { Ref : Vpc }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ProjectName }
                - { Ref: EnvironmentName }
                - "rtb"
                - "public"

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: { "Ref": "Vpc" }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ProjectName }
                - { Ref: EnvironmentName }
                - "rtb"
                - "private"

  RoutePublicToInternet:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      RouteTableId:  { Ref: PublicRouteTable }
      GatewayId:     { Ref: InternetGateway }

  PublicSubnetAZ0:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { Ref: Vpc }
      AvailabilityZone: { "Fn::Select": [ "0", { "Fn::GetAZs": "" } ] }
      MapPublicIpOnLaunch: "true"
      CidrBlock: { Ref: PublicSubnetAZ0Cidr }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ProjectName }
                - { Ref: EnvironmentName }
                - "public"
                - { "Fn::Select": [ "0", { "Fn::GetAZs": "" } ] }
  SubnetRouteTableAssociationPublicAZ0:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: { Ref: PublicSubnetAZ0 }
      RouteTableId: { Ref: PublicRouteTable }

  PrivateSubnetAZ0:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { Ref: Vpc }
      AvailabilityZone: { "Fn::Select": [ "0", { "Fn::GetAZs": "" } ] }
      CidrBlock: { Ref: PrivateSubnetAZ0Cidr }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ProjectName }
                - { Ref: EnvironmentName }
                - "private"
                - { "Fn::Select": [ "0", { "Fn::GetAZs": "" } ] }
  SubnetRouteTableAssociationPrivateAZ0:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: { Ref: PrivateSubnetAZ0 }
      RouteTableId: { Ref: PrivateRouteTable }

  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { Ref: Vpc }
      AvailabilityZone: { "Fn::Select": [ "1", { "Fn::GetAZs": "" } ] }
      MapPublicIpOnLaunch: "true"
      CidrBlock: { Ref: PublicSubnetAZ1Cidr }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ProjectName }
                - { Ref: EnvironmentName }
                - "public"
                - { "Fn::Select": [ "1", { "Fn::GetAZs": "" } ] }
  SubnetRouteTableAssociationPublicAZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: { Ref: PublicSubnetAZ1 }
      RouteTableId: { Ref: PublicRouteTable }

  PrivateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { Ref: Vpc }
      AvailabilityZone: { "Fn::Select": [ "1", { "Fn::GetAZs": "" } ] }
      CidrBlock: { Ref: PrivateSubnetAZ1Cidr }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ProjectName }
                - { Ref: EnvironmentName }
                - "private"
                - { "Fn::Select": [ "1", { "Fn::GetAZs": "" } ] }
  SubnetRouteTableAssociationPrivateAZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: { Ref: PrivateSubnetAZ1 }
      RouteTableId: { Ref: PrivateRouteTable }


Outputs:
  VpcIdExport:
    Value: { Ref: Vpc }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ProjectName }
            - { Ref: EnvironmentName }
            - "VpcId"

  PublicSubnetAZ0Export:
    Value: { Ref: PublicSubnetAZ0 }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ProjectName }
            - { Ref: EnvironmentName }
            - PublicSubnetAZ0

  PrivateSubnetAZ0Export:
    Value: { Ref: PrivateSubnetAZ0 }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ProjectName }
            - { Ref: EnvironmentName }
            - PrivateSubnetAZ0

  PublicSubnetAZ1Export:
    Value: { Ref: PublicSubnetAZ1 }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ProjectName }
            - { Ref: EnvironmentName }
            - PublicSubnetAZ1

  PrivateSubnetAZ1Export:
    Value: { Ref: PrivateSubnetAZ1 }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ProjectName }
            - { Ref: EnvironmentName }
            - PrivateSubnetAZ1

