AWSTemplateFormatVersion: "2010-09-09"

Description: S3 Web Bucket for public setup guide

Parameters:
  ProjectName:
    Type: String
    Description: Name for this project; e.g. downtime-notifier, dynamodb-scaler

  EnvironmentName:
    Type: String
    Description: Name for this environment; e.g. development, staging, production

  BucketName:
    Type: String
    Description: Name of the Bucket to create

Resources:
  WebBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: { Ref: BucketName }
      AccessControl: PublicRead
      WebsiteConfiguration: 
        IndexDocument: "index.html"
        ErrorDocument: "error.html"
    DeletionPolicy: Retain
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebBucket
                - /*
      Bucket: !Ref WebBucket
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - WebBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  Bucket:
    Value: { Ref: WebBucket }
  BucketArn:
    Value:
      "Fn::GetAtt": [WebBucket, Arn]
